# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helper_pb2 as helper__pb2


class PrimesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestAccuracy = channel.unary_unary(
                '/helper.Primes/TestAccuracy',
                request_serializer=helper__pb2.Empty.SerializeToString,
                response_deserializer=helper__pb2.AccuracyResponse.FromString,
                )


class PrimesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestAccuracy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestAccuracy': grpc.unary_unary_rpc_method_handler(
                    servicer.TestAccuracy,
                    request_deserializer=helper__pb2.Empty.FromString,
                    response_serializer=helper__pb2.AccuracyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helper.Primes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Primes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestAccuracy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helper.Primes/TestAccuracy',
            helper__pb2.Empty.SerializeToString,
            helper__pb2.AccuracyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
