# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helper.proto',
  package='helper',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0chelper.proto\x12\x06helper\"\x07\n\x05\x45mpty\"2\n\x10\x41\x63\x63uracyResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\x12\x0c\n\x04loss\x18\x02 \x01(\x02\x32\x41\n\x06Primes\x12\x37\n\x0cTestAccuracy\x12\r.helper.Empty\x1a\x18.helper.AccuracyResponseb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='helper.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=31,
)


_ACCURACYRESPONSE = _descriptor.Descriptor(
  name='AccuracyResponse',
  full_name='helper.AccuracyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='helper.AccuracyResponse.accuracy', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loss', full_name='helper.AccuracyResponse.loss', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AccuracyResponse'] = _ACCURACYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'helper_pb2'
  # @@protoc_insertion_point(class_scope:helper.Empty)
  })
_sym_db.RegisterMessage(Empty)

AccuracyResponse = _reflection.GeneratedProtocolMessageType('AccuracyResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACCURACYRESPONSE,
  '__module__' : 'helper_pb2'
  # @@protoc_insertion_point(class_scope:helper.AccuracyResponse)
  })
_sym_db.RegisterMessage(AccuracyResponse)



_PRIMES = _descriptor.ServiceDescriptor(
  name='Primes',
  full_name='helper.Primes',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=85,
  serialized_end=150,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestAccuracy',
    full_name='helper.Primes.TestAccuracy',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ACCURACYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRIMES)

DESCRIPTOR.services_by_name['Primes'] = _PRIMES

# @@protoc_insertion_point(module_scope)
