# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primes.proto',
  package='helper',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cprimes.proto\x12\x06helper\"\x07\n\x05\x45mpty\"-\n\x0f\x41\x63\x63uracyRequest\x12\x1a\n\x12ndarray_parameters\x18\x01 \x01(\x0c\"2\n\x10\x41\x63\x63uracyResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\x12\x0c\n\x04loss\x18\x02 \x01(\x02\"J\n\x16lossAndAccuracyRequest\x12\x0c\n\x04\x63ids\x18\x01 \x03(\t\x12\x0e\n\x06losses\x18\x02 \x03(\x02\x12\x12\n\naccuracies\x18\x03 \x03(\x02\"\x1d\n\x0bServerReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9c\x01\n\x06Primes\x12\x46\n\x0fgetNextStepLoss\x12\x1e.helper.lossAndAccuracyRequest\x1a\x13.helper.ServerReply\x12J\n\x13getServerClientLoss\x12\x1e.helper.lossAndAccuracyRequest\x1a\x13.helper.ServerReplyb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='helper.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=31,
)


_ACCURACYREQUEST = _descriptor.Descriptor(
  name='AccuracyRequest',
  full_name='helper.AccuracyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray_parameters', full_name='helper.AccuracyRequest.ndarray_parameters', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=78,
)


_ACCURACYRESPONSE = _descriptor.Descriptor(
  name='AccuracyResponse',
  full_name='helper.AccuracyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='helper.AccuracyResponse.accuracy', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loss', full_name='helper.AccuracyResponse.loss', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=130,
)


_LOSSANDACCURACYREQUEST = _descriptor.Descriptor(
  name='lossAndAccuracyRequest',
  full_name='helper.lossAndAccuracyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cids', full_name='helper.lossAndAccuracyRequest.cids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='losses', full_name='helper.lossAndAccuracyRequest.losses', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accuracies', full_name='helper.lossAndAccuracyRequest.accuracies', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=206,
)


_SERVERREPLY = _descriptor.Descriptor(
  name='ServerReply',
  full_name='helper.ServerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='helper.ServerReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=237,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AccuracyRequest'] = _ACCURACYREQUEST
DESCRIPTOR.message_types_by_name['AccuracyResponse'] = _ACCURACYRESPONSE
DESCRIPTOR.message_types_by_name['lossAndAccuracyRequest'] = _LOSSANDACCURACYREQUEST
DESCRIPTOR.message_types_by_name['ServerReply'] = _SERVERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'primes_pb2'
  # @@protoc_insertion_point(class_scope:helper.Empty)
  })
_sym_db.RegisterMessage(Empty)

AccuracyRequest = _reflection.GeneratedProtocolMessageType('AccuracyRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCURACYREQUEST,
  '__module__' : 'primes_pb2'
  # @@protoc_insertion_point(class_scope:helper.AccuracyRequest)
  })
_sym_db.RegisterMessage(AccuracyRequest)

AccuracyResponse = _reflection.GeneratedProtocolMessageType('AccuracyResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACCURACYRESPONSE,
  '__module__' : 'primes_pb2'
  # @@protoc_insertion_point(class_scope:helper.AccuracyResponse)
  })
_sym_db.RegisterMessage(AccuracyResponse)

lossAndAccuracyRequest = _reflection.GeneratedProtocolMessageType('lossAndAccuracyRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOSSANDACCURACYREQUEST,
  '__module__' : 'primes_pb2'
  # @@protoc_insertion_point(class_scope:helper.lossAndAccuracyRequest)
  })
_sym_db.RegisterMessage(lossAndAccuracyRequest)

ServerReply = _reflection.GeneratedProtocolMessageType('ServerReply', (_message.Message,), {
  'DESCRIPTOR' : _SERVERREPLY,
  '__module__' : 'primes_pb2'
  # @@protoc_insertion_point(class_scope:helper.ServerReply)
  })
_sym_db.RegisterMessage(ServerReply)



_PRIMES = _descriptor.ServiceDescriptor(
  name='Primes',
  full_name='helper.Primes',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=240,
  serialized_end=396,
  methods=[
  _descriptor.MethodDescriptor(
    name='getNextStepLoss',
    full_name='helper.Primes.getNextStepLoss',
    index=0,
    containing_service=None,
    input_type=_LOSSANDACCURACYREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getServerClientLoss',
    full_name='helper.Primes.getServerClientLoss',
    index=1,
    containing_service=None,
    input_type=_LOSSANDACCURACYREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRIMES)

DESCRIPTOR.services_by_name['Primes'] = _PRIMES

# @@protoc_insertion_point(module_scope)
